[package]
name = "ratatui-kit"
version = "0.4.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/yexiyue/ratatui-kit"
description = "A framework for building interactive terminal user interfaces with ratatui"
authors = ["yexiyue <yexiyue666@qq.com>"]

[dependencies]
futures = "0.3.31"
generational-box = "0.6.2"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
any_key = "0.1.1"
ratatui-kit-macros = { version = "0.4.0", path = "../ratatui-kit-macros" }
tui-textarea = { version = "0.7.0", optional = true, features = ["crossterm"] }
crossterm = { version = "0.28.0", features = ["event-stream"] }
regex = { version = "1.11.1", optional = true }

[features]
default = []
textarea = ["tui-textarea"]
router = ["regex", "ratatui-kit-macros/router"]
store = ["ratatui-kit-macros/store"]

full = ["textarea", "router", "store", "ratatui-kit-macros/full"]
