[package]
name = "ratatui-kit-macros"
version = "0.4.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/yexiyue/ratatui-kit"
description = "ratatui-kit macros"
authors = ["yexiyue <yexiyue666@qq.com>"]

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4"] }

[lib]
proc-macro = true

[features]
default = []
router = []
store = []

full = ["router", "store"]
